services:
###############
#  logs2mqtt   #
###############
  logs2mqtt:
    container_name: logs2mqtt
    image: william1608/logs2mqtt:$VERSION
    volumes:
      - /var/log/auth.log:/var/log/auth.log
      - /etc/localtime:/etc/localtime:ro
    env_file: ./.env
